{"name": "test_login[datayaml2]", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('test_url', <FixtureRequest for <Function test_login[datayaml2]>>)", "trace": "file D:\\python_Code\\pythonProject\\pythonclasses\\one\\day04\\webui_auto_base\\testcases\\test_login.py, line 26\n      @pytest.mark.parametrize(\"datayaml\",testData)\n      def test_login(self,datayaml,setup_teardown,assert_utils,test_url):\nE       fixture 'test_url' not found\n>       available fixtures: _session_faker, assert_utils, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, check, db, doctest_namespace, env_vars, extra, faker, faker_locale, include_metadata_in_junit_xml, ini, level, metadata, monkeypatch, owner, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, setup_teardown, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\python_Code\\pythonProject\\pythonclasses\\one\\day04\\webui_auto_base\\testcases\\test_login.py:26"}, "description": "\n        登录测试\n        :param datayaml: 加载login_data登录测试数据\n        :return:\n        ", "parameters": [{"name": "datayaml", "value": "{'id': 'test_login001.3', 'detail': '密码为空登录', 'screenshot': 'pawd_empty', 'data': {'username': 13511112222, 'password': ''}, 'check': ['请输入密码']}"}], "start": 1678461167320, "stop": 1678461167320, "uuid": "fc576d49-0997-4b0d-948a-a03bd6b7085e", "historyId": "d74ee31f8e025b0828c3cbb71b1d9085", "testCaseId": "95f7d5ffd6555b9dfe3d54dca0579a7a", "fullName": "testcases.test_login.TestUIAUTO#test_login", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestUIAUTO"}, {"name": "host", "value": "瑛智的工作电脑"}, {"name": "thread", "value": "77744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}