{"uuid": "9ce4b527-8292-473a-8519-64b225198ee9", "children": ["7bc6c335-1eb2-432e-92ac-9c6cb413e763", "2cc9985f-6fe8-40fa-8ac4-c4e394dfccef", "4c3ea6fc-f144-47e8-b3ca-9199a0924140", "72995ac3-de75-460d-b233-fe6e7f745083", "c465e734-83f5-4def-be27-9a269def0861"], "befores": [{"name": "setup_teardown", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 109\nCurrent browser version is 111.0.5563.64 with binary path C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\t(No symbol) [0x01146643]\n\t(No symbol) [0x010DBE21]\n\t(No symbol) [0x00FDDA9D]\n\t(No symbol) [0x01002911]\n\t(No symbol) [0x00FFD630]\n\t(No symbol) [0x00FFA899]\n\t(No symbol) [0x01036917]\n\t(No symbol) [0x0103655C]\n\t(No symbol) [0x0102FB76]\n\t(No symbol) [0x010049C1]\n\t(No symbol) [0x01005E5D]\n\tGetHandleVerifier [0x013BA142+2497106]\n\tGetHandleVerifier [0x013E85D3+2686691]\n\tGetHandleVerifier [0x013EBB9C+2700460]\n\tGetHandleVerifier [0x011F3B10+635936]\n\t(No symbol) [0x010E4A1F]\n\t(No symbol) [0x010EA418]\n\t(No symbol) [0x010EA505]\n\t(No symbol) [0x010F508B]\n\tBaseThreadInitThunk [0x765D6BD9+25]\n\tRtlGetFullPathName_UEx [0x77D08FD2+1218]\n\tRtlGetFullPathName_UEx [0x77D08F9D+1165]\n\n", "trace": "  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\python_Code\\pythonProject\\pythonclasses\\one\\day04\\webui_auto_base\\conftest.py\", line 30, in setup_teardown\n    driver = webdriver.Chrome()\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    service_log_path, service, keep_alive)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 99, in __init__\n    options=options)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\syz\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1678460784376, "stop": 1678460787536}], "start": 1678460784376, "stop": 1678460787974}