{"name": "test_login[datayaml1]", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('test_url', <FixtureRequest for <Function test_login[datayaml1]>>)", "trace": "file D:\\python_Code\\pythonProject\\pythonclasses\\one\\day04\\webui_auto_base\\testcases\\test_login.py, line 26\n      @pytest.mark.parametrize(\"datayaml\",testData)\n      def test_login(self,datayaml,setup_teardown,assert_utils,test_url):\nE       fixture 'test_url' not found\n>       available fixtures: _session_faker, assert_utils, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, check, db, doctest_namespace, env_vars, extra, faker, faker_locale, include_metadata_in_junit_xml, ini, level, metadata, monkeypatch, owner, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, setup_teardown, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\python_Code\\pythonProject\\pythonclasses\\one\\day04\\webui_auto_base\\testcases\\test_login.py:26"}, "description": "\n        登录测试\n        :param datayaml: 加载login_data登录测试数据\n        :return:\n        ", "parameters": [{"name": "datayaml", "value": "{'id': 'test_login001.2', 'detail': '用户名为空登录', 'screenshot': 'user_empty', 'data': {'username': '', 'password': 'aa'}, 'check': ['请输入账户名']}"}], "start": 1678461167298, "stop": 1678461167298, "uuid": "bd2c3ae6-3249-43b5-bd66-4869312a94cd", "historyId": "0c68670e24706695e5b7476e2719558f", "testCaseId": "95f7d5ffd6555b9dfe3d54dca0579a7a", "fullName": "testcases.test_login.TestUIAUTO#test_login", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestUIAUTO"}, {"name": "host", "value": "瑛智的工作电脑"}, {"name": "thread", "value": "77744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_login"}]}